---
- name: Adds repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
    update_cache: true

- name: Auto accept licence
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: boolean
    value: 'true'

- name: Installs latest java
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - ca-certificates
    - oracle-java8-installer
