- name: Adds repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Auto accept licence
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: select
    value: true

- name: Installs latest java
  apt: pkg={{ item }} state=latest
  with_items:
    - ca-certificates
    - oracle-java8-installer