---
- name: Adds repository
  apt_repository:
    repo: 'ppa:linuxuprising/java'
    update_cache: true

- name: Auto accept licence
  debconf:
    name: oracle-java14-installer
    question: shared/accepted-oracle-license-v1-2
    vtype: boolean
    value: 'true'

- name: Installs latest java
  apt:
    pkg:
      - ca-certificates
      - oracle-java14-installer
    state: present
